### ISSUE TITLE
Where to find *.vsix files?

### ISSUE THREAD

**Issue by ashleykleynhans** [kodxana/madiator-docker-runpod#2]
**Describe the bug**
On line 50 of `official-templates/better-pytorch/Dockerfile`"

```
# Copy VSIX files to the Docker image
COPY vsix/*.vsix /tmp/
```

But these files and folder do not seem to exist in the repo?

**To Reproduce**
N/A

**Expected behavior**
vsix folder and files to be added to repo, or a comment to be added to explain where to get them if we want to build the Docker image ourselves.

**Comment by ashleykleynhans** [comment]
Never mind, found them.

https://marketplace.visualstudio.com/items?itemName=vscode-ext.sync-rsync
https://marketplace.visualstudio.com/items?itemName=RSIP-Vision.nvidia-smi-plus

**Comment by kodxana** [comment]
@ashleykleynhans they are optional and can be hashed out

**Comment by ashleykleynhans** [comment]
> @ashleykleynhans they are optional and can be hashed out

Thanks, I found them anyway as I mentioned above and closed the issue.
